set nocompatible " disable vi mode
set backspace=2 " backspace configuration
set number " line numbers on the left
set autoindent
set smartindent
set incsearch " move cursor while typing search pattern
set hlsearch
set ignorecase
set smartcase
set showcmd " show commands while typing them
set laststatus=2 " always display the status bar
set statusline=[%02n]\ %f\ %(\[%M%R%H]%)\ %y\ %{''.&fileencoding}\ %=\ %4l,%02c%2V\ %P%*
set splitbelow " new split buffers are below the current one
set splitright " new vertical split buffer are on the right of the current one
set history=1000 " bigger history
set wildmenu " display a menu when hitting <TAB>
set wildmode=longest:full " display wildmenu even with commands
set scrolloff=3 " maintain context around the cursor when scrolling
set list listchars=tab:»·,trail:·,extends:…,nbsp:‗ " indicate spaces spaces
syntax on

set guifont=guifont=Monaco:h10
set guioptions-=m
set guioptions-=T
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R

set expandtab
set sw=2
set sts=2

nnoremap <C-l> :nohlsearch<CR>:Rooter<CR><C-l>

" QFEnter settings
let g:qfenter_open_map = ['o']
let g:qfenter_vopen_map = ['v']
let g:qfenter_hopen_map = ['h']
let g:qfenter_topen_map = ['t']
autocmd BufReadPost quickfix nmap <buffer> q <C-w>p:cclose<CR>
autocmd BufReadPost quickfix nmap <buffer> <CR> o<C-w>p
autocmd BufReadPost quickfix nmap <buffer> <Tab> v:cclose<CR>

" Ag settings
let g:ag_apply_lmappings=0
let g:ag_apply_qmappings=0

" FZF settings
nnoremap <C-f> :Files<CR>
nnoremap <C-g> :Lines<CR>

" NERDTree settings
nnoremap <C-t> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
